In [2]:
import pyworld as pw

In [3]:
import librosa

In [4]:
import numpy as np

In [5]:
from os.path import join

In [6]:
from os import getcwd as __dir__

In [7]:
fft_size = 16000

In [8]:
file = join(__dir__(),  'test2.wav')

In [9]:
wave, _ = librosa.load(file, sr=fft_size, mono=True, dtype=np.float64)

In [10]:
np.array(wave).shape

(63813,)

In [13]:
_f0, t = pw.dio(wave, fft_size, f0_ceil=500)

In [14]:
_f0

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        , 178.43572289, 162.58380998, 159.10942065,
       152.41470379, 142.92790277, 137.58731984, 137.57113877,
       133.44027531, 133.93224506, 133.61518824, 127.6473194 ,
       127.16901476, 127.59244052, 125.84697196, 125.58778679,
       124.05958511, 124.89365914, 127.13883364, 127.02302591,
       125.53172222, 128.69314244, 131.39521543, 132.95335919,
       135.72562532, 135.9956087 , 135.42470432, 134.7424071 ,
       136.29063411, 138.95498814, 139.46068196, 137.35

In [15]:
t

array([0.   , 0.005, 0.01 , 0.015, 0.02 , 0.025, 0.03 , 0.035, 0.04 ,
       0.045, 0.05 , 0.055, 0.06 , 0.065, 0.07 , 0.075, 0.08 , 0.085,
       0.09 , 0.095, 0.1  , 0.105, 0.11 , 0.115, 0.12 , 0.125, 0.13 ,
       0.135, 0.14 , 0.145, 0.15 , 0.155, 0.16 , 0.165, 0.17 , 0.175,
       0.18 , 0.185, 0.19 , 0.195, 0.2  , 0.205, 0.21 , 0.215, 0.22 ,
       0.225, 0.23 , 0.235, 0.24 , 0.245, 0.25 , 0.255, 0.26 , 0.265,
       0.27 , 0.275, 0.28 , 0.285, 0.29 , 0.295, 0.3  , 0.305, 0.31 ,
       0.315, 0.32 , 0.325, 0.33 , 0.335, 0.34 , 0.345, 0.35 , 0.355,
       0.36 , 0.365, 0.37 , 0.375, 0.38 , 0.385, 0.39 , 0.395, 0.4  ,
       0.405, 0.41 , 0.415, 0.42 , 0.425, 0.43 , 0.435, 0.44 , 0.445,
       0.45 , 0.455, 0.46 , 0.465, 0.47 , 0.475, 0.48 , 0.485, 0.49 ,
       0.495, 0.5  , 0.505, 0.51 , 0.515, 0.52 , 0.525, 0.53 , 0.535,
       0.54 , 0.545, 0.55 , 0.555, 0.56 , 0.565, 0.57 , 0.575, 0.58 ,
       0.585, 0.59 , 0.595, 0.6  , 0.605, 0.61 , 0.615, 0.62 , 0.625,
       0.63 , 0.635,

In [16]:
f0 = pw.stonemask(wave, _f0, t, fft_size)

In [17]:
f0

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        , 170.50570602, 184.25233439, 157.57667885,
       154.32509408, 144.50047519, 139.85933399, 136.22636523,
       133.33378456, 131.95504206, 130.30736209, 127.83998161,
       126.71019103, 126.23943681, 124.82142202, 124.13447811,
       123.37112388, 123.6544557 , 124.74261485, 127.14974436,
       128.19338728, 130.51689228, 132.49929837, 132.39348549,
       134.08272812, 136.09938736, 135.94184376, 136.06469581,
       137.83891991, 139.7206748 , 138.6960883 , 135.73

In [18]:
sp = pw.cheaptrick(wave, f0, t, fft_size)

In [19]:
sp

array([[8.11568690e-07, 8.11705473e-07, 8.12110744e-07, ...,
        2.01557280e-08, 2.01021407e-08, 2.00843144e-08],
       [1.01554742e-04, 1.01541500e-04, 1.01505586e-04, ...,
        2.14432467e-08, 2.11979972e-08, 2.11166178e-08],
       [8.07896821e-05, 8.07736368e-05, 8.07256021e-05, ...,
        7.29967867e-08, 7.20103291e-08, 7.16856629e-08],
       ...,
       [2.11309313e-04, 2.11336469e-04, 2.11417710e-04, ...,
        6.69491806e-08, 6.67060878e-08, 6.66256775e-08],
       [1.58557880e-04, 1.58517818e-04, 1.58403113e-04, ...,
        9.98884195e-07, 1.00070508e-06, 1.00130980e-06],
       [2.73730041e-05, 2.73725016e-05, 2.73707634e-05, ...,
        3.51605066e-08, 3.47211082e-08, 3.45763431e-08]])

In [20]:
ap = pw.d4c(wave, f0, t, fft_size)

In [25]:
np.array(ap).shape, ap

((798, 513), array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]))